[package]
name = "gmod-developer-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
paris = { version = "1.5", features = ["timestamps", "macros", "no_logger"] }
regex = "1"
inquire = "0.5.3"
itertools = "0.10.5"